### ISSUE TITLE
BRISQUE returns negative score

### ISSUE THREAD

**Issue by sangrockEG** [ocampor/notebooks#9]
First of all, thanks for your implementation.
I hired it to check quality of endoscopy image, which is no-reference task.
But I found that some of my images got negative scores with the BRISQUE algorithm.

![1022n](https://user-images.githubusercontent.com/40968875/64144812-33e79a80-ce51-11e9-88f0-ca8e1734d08a.png)

BRISQUE returns smaller score for good (realistic) image, and returns larger score for bad (distorted) image in the range of [0,100], right?
But above image got the score of -7.49863.
How should I interpret this negative score? Is the image too good or somewhat?

**Comment by ocampor** [comment]
### Problem
It is amazing you are trying to use the code in such a cool application. The problem is that BRISUE is based on Natural Scene Statistics (take a look to [this article]( https://en.wikipedia.org/wiki/Scene_statistics)).

### Solution 
For medical image applications you need to retrain (which doesn't guarantee that it's gonna work) or use a different model. I explain some methodologies based on feature learning in [this medium aticle](https://medium.com/@ocampor/advanced-methods-for-iqa-37581ec3c31f) and working on implementing one of them in [this repository](https://github.com/ocampor/image-quality/blob/master/notebooks/train-diqa-base.ipynb).

Take a look and let me know what you think.

**Comment by sangrockEG** [comment]
I'm quite new in a feild of IQA, so I really appreciate for your kind explanation.

I understand that the BRISQUE function may not work well with my task, since the BRISQUE is trained on certain dataset (LIVE IQA or somewhat) which do not include any medical-related image.

So I think I need to build new dataset and train the model on it as you recommended.

My plan is building the pristine dataset with high-quality endoscopy image with full resolution, first.
And then add artificial distortions on them, where the magnitude of the distortion will be a score of the distorted image. So, if the score of certain image is high, it means that the image includes extreme distortion. YES. This works as an alternative of DMOS.

I think if the model is trained on above dataset, then the model might can check the quality of arbitrary endoscopy image with relative low-quality. (For this, I should design the distortion very carefully.) As many other learning-based method, nobody cannot sure, but I think this strategy is worthfull to test.

Thanks for your implementation and comment again.
